/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103c6_GPIO_driver.h"
#include "stm32f103c6_EXTI_driver.h"
#include "lcd.h"
#include "keypad.h"

uint32_t IRQ_Flag=0;
void interrupt_handler(void);


int main(void)
{
	GPIOA_CLK_ENB;
	GPIOB_CLK_ENB;
	AFIO_CLK_ENB;
	lcd_init();
	Keypad_init();
	EXTI_Config My_interrupt;
	My_interrupt.My_EXTI_pin=EXTI9PB9;
	My_interrupt.EXTI_state=EXTI_enable;
	My_interrupt.EXTI_trigger=EXTI_falling;
	My_interrupt.ISR_func=&interrupt_handler;
	MCAL_EXTI_GPIO_Init(&My_interrupt);

	while(1){
			if(IRQ_Flag){
			lcd_clear_screen();
			IRQ_Flag=0;
			}
		}
}

void interrupt_handler(void)
{
	IRQ_Flag=1;
		lcd_write_string("IRQ EXTI9 IS HAPPEND _|- ");
		wait_ms(3000);
}
