/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103c6_GPIO_driver.h"

#include "lcd.h"
#include "keypad.h"
#include "seven_seg.h"


int main(void)
{
	GPIOA_CLK_ENB;
	GPIOB_CLK_ENB;

	lcd_init();


	lcd_write_string("Learn in depth. Drivers made by Michel Adel");
	wait_ms(30);
	lcd_clear_screen();

	uint8_t key_pressed;
	uint8_t seg_num[]={ ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	uint8_t LCD_Numbers[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};


	for (uint8_t i = 0; i < 11; i++)
		{
			MCAL_GPIO_write_port(seg_num[i]<<9, GPIOB);

			lcd_write_char(LCD_Numbers[i]);

			wait_ms(100);
		}

	lcd_clear_screen();

	Keypad_init();
	while(1){

		key_pressed = keypad_getchar();

		switch(key_pressed){
		case 'A':
			break;
		case '?':
			lcd_clear_screen();
			break;
		default:
			lcd_write_char(key_pressed);
			break;
		}
	}
}

