/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f10c6_RCC_driver.h"
#include "stm32f103c6_GPIO_driver.h"
#include "stm32f103c6_USART_driver.h"
#include "lcd.h"


uint16_t mychar;
void USART_fun(){
	MCAL_USART_recieve_data(USART1, &mychar, disable);
	MCAL_USART_send_data(USART1, &mychar, enable);
}

int main(void)
{
	GPIOA_CLK_ENB;
	USART1_Config.BaudRate=USART_BaudRate_115200;
	USART1_Config.Parity=USART_No_Parity;
	USART1_Config.HWFlowCTRL=USART_HWFlowCTRL_None;
	USART1_Config.Stopbits=USART_StopBit_1;
	USART1_Config.USART_Mode=USART_Mode_TX_RX;
	USART1_Config.Payload_length=USART_Payload_8bit;
	USART1_Config.IRQ_Enable=USART_IRQ_Enable_RXNE;
	USART1_Config.P_IRQ_CallBack=&USART_fun;
	MCAL_USART_init(&USART1_Config, USART1);
	MCAL_USART_GPIO_setpins(USART1);
	while(1){

	}
}

