/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define MCU_act_as_Master
//#define MCU_act_as_Slave


#include "stm32f103c6_GPIO_driver.h"
#include "stm32f103c6_USART_driver.h"
#include "stm32f103c6_SPI_driver.h"

unsigned char ch;

void clock_init(){
	GPIOA_CLK_ENB;
	GPIOB_CLK_ENB;
	AFIO_CLK_ENB;
}


void SPI_callback(struct S_IRQ_SRC irq_src){
#ifdef MCU_act_as_Slave

	if(irq_src.RXNE){
		ch=0xf;
		MCAL_SPI_TX_RX(SPI1, &ch, Polling_enable);
		MCAL_USART_send_data(USART1, &ch, enable);
	}

#endif
}


void USART_callback(void){
#ifdef MCU_act_as_Master

	MCAL_USART_recieve_data(USART1, &ch, enable);
	MCAL_USART_send_data(USART1, &ch, enable);

	MCAL_GPIO_write_pin(0, GPIOA, GPIO_PIN4);
	MCAL_SPI_TX_RX(SPI1, &ch, Polling_enable);
	MCAL_GPIO_write_pin(0x1, GPIOA, GPIO_PIN4);
#endif

}


int main(void)
{
	clock_init();

	USART1_Config.BaudRate=USART_BaudRate_115200;
	USART1_Config.HWFlowCTRL=USART_HWFlowCTRL_None;
	USART1_Config.IRQ_Enable=USART_IRQ_Enable_RXNE;
	USART1_Config.P_IRQ_CallBack=USART_callback;
	USART1_Config.Parity=USART_No_Parity;
	USART1_Config.Payload_length=USART_Payload_8bit;
	USART1_Config.Stopbits=USART_StopBit_1;
	USART1_Config.USART_Mode=USART_Mode_TX_RX;

	MCAL_USART_init(&USART1_Config, USART1);
	MCAL_USART_GPIO_setpins(USART1);

	SPI_Config my_spi;
	my_spi.BaudRate_Prescaler=SPI_Baud_Rate_Scale_8;
	my_spi.CLK_Phase=SPI_CLK_Phase_2nd_edge;
	my_spi.CLK_Polarity=SPI_CLK_Polarity_High;
	my_spi.Communication_Mode=SPI_2_lines;
	my_spi.DataFrame=SPI_strt_MSB;
	my_spi.DataSize=SPI_Data_Size_8;

#ifdef MCU_act_as_Slave

	my_spi.Device_Mode=SPI_Mode_Slave;
	my_spi.IRQ_Enable=SPI_IRQ_Enable_RXNEIE;
	my_spi.NSS=SPI_NSS_Hard_Slave;
	my_spi.P_IRQ_CallBack=SPI_callback;

#endif

#ifdef MCU_act_as_Master

	my_spi.Device_Mode=SPI_Mode_Master;
	my_spi.IRQ_Enable=SPI_IRQ_Enable_None;
	my_spi.NSS=SPI_NSS_Soft_Set;


	GPIO_Pin_Config my_gpio;
	my_gpio.Pin_Mode=GPIO_MODE_Output_push_pull;
	my_gpio.Pin_Num=GPIO_PIN4;
	my_gpio.Pin_Out_speed=GPIO_Speed_10MHZ;
	MCAL_GPIO_init(GPIOA, &my_gpio);
	MCAL_GPIO_write_pin(0x1, GPIOA, GPIO_PIN4);

#endif
	MCAL_SPI_Init(SPI1, &my_spi);
	MCAL_SPI_Set_GPIO_Pins(SPI1);


	while(1){

	}
}

